name: Test iOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Change xcode version
      run: |
        sudo xcode-select -s '/Applications/Xcode_12_beta.app/Contents/Developer'

    - name: Check environment
      run: |
        xcodebuild -version
        instruments -s device
    # xcrun xctrace list devices

    - name: Run tests (iOS)
      run: xcodebuild test -scheme "PomodoroHub (iOS)" -destination 'platform=iOS Simulator,name=iPod touch (7th generation)'
